apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: python-app
        image: sagar/python-sample-app:v1
        env:
        - name: DB-PORT
          valueFrom:
           configMapKeyRef: 
            name: test-configmap
            key: db-port
        ports:
        - containerPort: 80
